In [1]:
from wequant.data_processing import FinancequotePl

# objects imoprted in lib.lib_dateprocess
import os, calendar
import polars as pl
import pandas as pd
from typing import Union, Literal
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
from plotly.subplots import make_subplots
from plotly.graph_objects import Figure

ModuleNotFoundError: No module named 'wequant.data_processing'

In [2]:
FQ = FinancequotePl()

In [7]:
#def filter_finance_quotes_by_date(
#self,
#specific_date: date = date.today(),
#inplace: bool = False
#) -> pl.DataFrame | None:
'''
FinancequotePl.dfから、指定日における最新日のデータを抽出する。
inplace = Falseの場合は、抽出結果をpl.DataFrameで返す。
inplace = Trueの場合は、抽出結果をPortfolioManager.dfにセットしてNoneを返す。
'''

# imoprt from wequant.data_processing

#para
self = FQ
specific_date = date.today()
inplace = False

In [8]:
FQ.filter_finance_quotes_by_date(specific_date, inplace)

shape: (3_722, 12)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ code ┆ date       ┆ total_shar ┆ expected_d ┆ … ┆ actual_BPS ┆ actual_CA ┆ next_sett ┆ last_sett │
│ ---  ┆ ---        ┆ es_num     ┆ ividend_yi ┆   ┆ ---        ┆ R         ┆ lement_da ┆ lement_da │
│ i64  ┆ date       ┆ ---        ┆ eld        ┆   ┆ f64        ┆ ---       ┆ te        ┆ te        │
│      ┆            ┆ f64        ┆ ---        ┆   ┆            ┆ f64       ┆ ---       ┆ ---       │
│      ┆            ┆            ┆ f64        ┆   ┆            ┆           ┆ date      ┆ date      │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1301 ┆ 2026-02-06 ┆ 1.20783e7  ┆ 2.9        ┆ … ┆ null       ┆ 36.5      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1332 ┆ 2026-02-06 ┆ 3.1243e8   ┆ 1.96       ┆ … ┆ null       ┆ 43.6      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1333 ┆ 2026-02-06 ┆ 1.51737e8  ┆ 2.5        ┆ … ┆ null       ┆ 33.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1375 ┆ 2026-02-06 ┆ 3.99107e7  ┆ 1.49       ┆ … ┆ null       ┆ 32.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1376 ┆ 2026-02-06 ┆ 1.17726e7  ┆ 2.53       ┆ … ┆ null       ┆ 50.7      ┆ 2026-05-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 9991 ┆ 2026-02-06 ┆ 3.37957e7  ┆ 3.9        ┆ … ┆ null       ┆ 61.9      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9993 ┆ 2026-02-06 ┆ 1.09608e7  ┆ 2.25       ┆ … ┆ null       ┆ 46.7      ┆ 2026-02-2 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 8         ┆           │
│ 9994 ┆ 2026-02-06 ┆ 1.08479e7  ┆ 3.32       ┆ … ┆ null       ┆ 52.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9996 ┆ 2026-02-06 ┆ 9.15264e6  ┆ 2.06       ┆ … ┆ null       ┆ 73.8      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9997 ┆ 2026-02-06 ┆ 9.72445e7  ┆ 3.14       ┆ … ┆ null       ┆ 45.2      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [12]:
#body
df = self.df

df = df.filter(
    pl.col("date") <= specific_date
)
latest_date = df["date"].max()

df = df.filter(
    pl.col("date") == latest_date
)

if inplace:
    self.df = df
    #return
else:
    #return df
    pass

In [13]:
self.df

shape: (3_722, 12)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ code ┆ date       ┆ total_shar ┆ expected_d ┆ … ┆ actual_BPS ┆ actual_CA ┆ next_sett ┆ last_sett │
│ ---  ┆ ---        ┆ es_num     ┆ ividend_yi ┆   ┆ ---        ┆ R         ┆ lement_da ┆ lement_da │
│ i64  ┆ date       ┆ ---        ┆ eld        ┆   ┆ f64        ┆ ---       ┆ te        ┆ te        │
│      ┆            ┆ f64        ┆ ---        ┆   ┆            ┆ f64       ┆ ---       ┆ ---       │
│      ┆            ┆            ┆ f64        ┆   ┆            ┆           ┆ date      ┆ date      │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1301 ┆ 2026-02-06 ┆ 1.20783e7  ┆ 2.9        ┆ … ┆ null       ┆ 36.5      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1332 ┆ 2026-02-06 ┆ 3.1243e8   ┆ 1.96       ┆ … ┆ null       ┆ 43.6      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1333 ┆ 2026-02-06 ┆ 1.51737e8  ┆ 2.5        ┆ … ┆ null       ┆ 33.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1375 ┆ 2026-02-06 ┆ 3.99107e7  ┆ 1.49       ┆ … ┆ null       ┆ 32.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 1376 ┆ 2026-02-06 ┆ 1.17726e7  ┆ 2.53       ┆ … ┆ null       ┆ 50.7      ┆ 2026-05-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ …    ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 9991 ┆ 2026-02-06 ┆ 3.37957e7  ┆ 3.9        ┆ … ┆ null       ┆ 61.9      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9993 ┆ 2026-02-06 ┆ 1.09608e7  ┆ 2.25       ┆ … ┆ null       ┆ 46.7      ┆ 2026-02-2 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 8         ┆           │
│ 9994 ┆ 2026-02-06 ┆ 1.08479e7  ┆ 3.32       ┆ … ┆ null       ┆ 52.7      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9996 ┆ 2026-02-06 ┆ 9.15264e6  ┆ 2.06       ┆ … ┆ null       ┆ 73.8      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
│ 9997 ┆ 2026-02-06 ┆ 9.72445e7  ┆ 3.14       ┆ … ┆ null       ┆ 45.2      ┆ 2026-03-3 ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆ 1         ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
#### def print_finance_info(
####    self, 
####    code: int,
####    pricelist_type: Literal[
####        "raw_pricelist", 
####        "reviced_pricelist"
####    ] = "raw_pricelist",
####    valuation_date: date = date.today()
#### ) -> None:

# aditional import
from datetime import date
DATEFORMAT2 = "%Y年%m月%d日"
import polars as pl

# set para
self = FPL
code = 3422
pricelist_type = "raw_pricelist"
valuation_date = date.today()

In [11]:
###
### body
###
# タイトルの出力
company_name = get_companyname(code)
print(f'{company_name}({code})の銘柄情報\n')

# 株価情報の出力
PPL = PricelistPl(f'{pricelist_type}.parquet')
tup = PPL.get_latest_dealingdate_and_price(code, valuation_date)
stock_price = tup[1]
print(f'終値: {stock_price}円({tup[0].strftime(DATEFORMAT2)})')


# その他指標(finance_quoteデータが存在しない場合は、出力をスキップ)
df = self.df
if not "market_cap" in df.columns:
    self.with_columns_market_cap()
    df = self.df

df = df.filter(pl.col("code")==code)\
    .filter(pl.col("date")<=valuation_date)

if df.shape[0] == 0:
    print(f'{company_name}({code})は、{valuation_date.strftime(DATEFORMAT2)}以前の財務データがないため、財務情報の出力をスキップ')

    # debug
    # return
    pass

df = df.filter(pl.col("date")==pl.col("date").max())
quoted_date = df.select(["date"]).row(0)[0]
# 予想配当利回り
expected_dividened_yield = df.select(["expected_dividend_yield"]).row(0)[0]
print(f'予想配当利回り: {expected_dividened_yield}%({quoted_date.strftime(DATEFORMAT2)})')
# 予想PER
expected_PER = df.select(["expected_PER"]).row(0)[0]
print(f'予想PER: {expected_PER}倍({quoted_date.strftime(DATEFORMAT2)})')
# 実績PBR
actual_PBR = df.select(["actual_PBR"]).row(0)[0]
print(f'実績PBR: {actual_PBR}倍({quoted_date.strftime(DATEFORMAT2)})')
# 自己資本比率
actual_CAR = df.select(["actual_CAR"]).row(0)[0]
print(f'自己資本比率: {actual_CAR}%({quoted_date.strftime(DATEFORMAT2)})')
# 予想ROE/予想ROA
actual_BPS = df.select(["actual_BPS"]).row(0)[0]
expected_EPS = df.select(["expected_EPS"]).row(0)[0]

if not expected_EPS is None and not actual_BPS is None and actual_BPS != 0:
    expected_ROE = 100*(expected_EPS / actual_BPS)
    expected_ROE = round(expected_ROE, 2)
    print(f'予想ROE: {expected_ROE}%({quoted_date.strftime(DATEFORMAT2)})')
    expected_ROA = expected_ROE * (actual_CAR/100)
    expected_ROA = round(expected_ROA, 2)
    print(f'予想ROA: {expected_ROA}%({quoted_date.strftime(DATEFORMAT2)})')
else:
    print(f'予想ROE: 決算予想がないため、表示不可')
    print(f'予想ROA: 決算予想がないため、表示不可')

#　時価総額
market_capitalization = df.select(["market_cap"]).row(0)[0]
if not market_capitalization is None:
    market_capitalization = round(market_capitalization/100, 1)
else:
    market_capitalization = "-"
print(f'時価総額: {market_capitalization}億円({quoted_date.strftime(DATEFORMAT2)})')

J-MAX(3422)の銘柄情報

終値: 413.0円(2025年11月17日)
予想配当利回り: 0.9%(2025年11月21日)
予想PER: 5.99倍(2025年11月21日)
実績PBR: 0.3倍(2025年11月21日)
自己資本比率: 32.2%(2025年11月21日)
予想ROE: 決算予想がないため、表示不可
予想ROA: 決算予想がないため、表示不可
時価総額: -億円(2025年11月21日)

In [10]:
df

shape: (1, 13)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ code ┆ date       ┆ total_shar ┆ expected_d ┆ … ┆ actual_CAR ┆ next_sett ┆ last_sett ┆ market_ca │
│ ---  ┆ ---        ┆ es_num     ┆ ividend_yi ┆   ┆ ---        ┆ lement_da ┆ lement_da ┆ p         │
│ i64  ┆ date       ┆ ---        ┆ eld        ┆   ┆ f64        ┆ te        ┆ te        ┆ ---       │
│      ┆            ┆ f64        ┆ ---        ┆   ┆            ┆ ---       ┆ ---       ┆ i64       │
│      ┆            ┆            ┆ f64        ┆   ┆            ┆ date      ┆ date      ┆           │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 3422 ┆ 2025-11-21 ┆ 1.18572e7  ┆ 0.9        ┆ … ┆ 32.2       ┆ 2026-03-3 ┆ null      ┆ null      │
│      ┆            ┆            ┆            ┆   ┆            ┆ 1         ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘