In [1]:
from wequant.data_processing import KessanPl

# objects inported in wequant.data_processing
import os, calendar
import polars as pl
import pandas as pd
from typing import Union, Literal
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
from plotly.subplots import make_subplots
from plotly.graph_objects import Figure

In [2]:
K = KessanPl()

In [3]:
#def filter_by_codes(
#self,
#codes: list[int]
#) -> None:
'''
KessanPl.dfをcodesで指定した銘柄のみに絞る
'''

# additional import

# set para
self = K
codes = [1301, 9997]

In [7]:
# test
K.filter_by_codes(codes)
K.df["code"].unique()

shape: (2,)
Series: 'code' [i64]
[
	1301
	9997
]

In [9]:
# body
self.df = self.df.filter(
    pl.col("code").is_in(codes)
)

In [10]:
self.df["code"].unique()

shape: (2,)
Series: 'code' [i64]
[
	1301
	9997
]

In [10]:
KPl.with_columns_columns_ratio(col1, col2)
KPl.df

shape: (176_408, 14)
┌──────┬─────────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬────────────┐
│ code ┆ settlement_ ┆ settlement ┆ announceme ┆ … ┆ quater ┆ sales_to_o ┆ s-to-p-rat ┆ s-to-p-rat │
│ ---  ┆ date        ┆ _type      ┆ nt_date    ┆   ┆ ---    ┆ rdinary_pr ┆ ion        ┆ io         │
│ i64  ┆ ---         ┆ ---        ┆ ---        ┆   ┆ i64    ┆ ofit_ratio ┆ ---        ┆ ---        │
│      ┆ date        ┆ str        ┆ date       ┆   ┆        ┆ ---        ┆ f64        ┆ f64        │
│      ┆             ┆            ┆            ┆   ┆        ┆ f64        ┆            ┆            │
╞══════╪═════════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 1301 ┆ 2017-03-31  ┆ 本         ┆ 2017-05-11 ┆ … ┆ -2     ┆ 63.78      ┆ 63.78      ┆ 63.78      │
│ 1301 ┆ 2018-03-31  ┆ 本         ┆ 2018-05-10 ┆ … ┆ 4      ┆ 57.42      ┆ 57.42      ┆ 57.42      │
│ 1301 ┆ 2018-09-30  ┆ 四         ┆ 2018-11-05 ┆ … ┆ 2      ┆ 102.93     ┆ 102.93     ┆ 102.93     │
│ 1301 ┆ 2018-12-31  ┆ 四         ┆ 2019-02-08 ┆ … ┆ 3      ┆ 30.33      ┆ 30.33      ┆ 30.33      │
│ 1301 ┆ 2019-03-31  ┆ 本         ┆ 2019-05-13 ┆ … ┆ 4      ┆ 57.77      ┆ 57.77      ┆ 57.77      │
│ …    ┆ …           ┆ …          ┆ …          ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 9997 ┆ 2024-12-31  ┆ 四         ┆ 2025-01-31 ┆ … ┆ 3      ┆ 13.48      ┆ 13.48      ┆ 13.48      │
│ 9997 ┆ 2025-03-31  ┆ 四         ┆ 2025-05-13 ┆ … ┆ 4      ┆ 11.48      ┆ 11.48      ┆ 11.48      │
│ 9997 ┆ 2025-03-31  ┆ 本         ┆ 2025-05-13 ┆ … ┆ 4      ┆ 15.91      ┆ 15.91      ┆ 15.91      │
│ 9997 ┆ 2026-03-31  ┆ 予         ┆ 2025-05-13 ┆ … ┆ 4      ┆ 15.9       ┆ 15.9       ┆ 15.9       │
│ 9997 ┆ 2025-06-30  ┆ 四         ┆ 2025-07-31 ┆ … ┆ 1      ┆ 40.4       ┆ 40.4       ┆ 40.4       │
└──────┴─────────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴────────────┘

In [8]:
###
### body
###

df = self.df

# validation
flg1 = col1 in df.columns
flg2 = col2 in df.columns
if not flg1:
    try:
        sys.exit(f"列{col1}は存在しません")
    except SystemExit as e:
        print("終了時メッセージ:", e)
if not flg2:
    try:
        sys.exit(f"列{col2}は存在しません")
    except SystemExit as e:
        print("終了時メッセージ:", e)

# 追加列名のセット
if new_col is None:
    new_col = f'{col1}_to_{col2}_ratio'

df = df.with_columns(
    (pl.col(col1) / pl.col(col2)).round(2).alias(new_col)
)

self.df = df

In [9]:
self.df

shape: (176_408, 12)
┌──────┬─────────────┬─────────────┬─────────────┬───┬────────────┬──────────┬────────┬────────────┐
│ code ┆ settlement_ ┆ settlement_ ┆ announcemen ┆ … ┆ reviced_ep ┆ dividend ┆ quater ┆ sales-ordi │
│ ---  ┆ date        ┆ type        ┆ t_date      ┆   ┆ s          ┆ ---      ┆ ---    ┆ nary_profi │
│ i64  ┆ ---         ┆ ---         ┆ ---         ┆   ┆ ---        ┆ f64      ┆ i64    ┆ t_ratio    │
│      ┆ date        ┆ str         ┆ date        ┆   ┆ f64        ┆          ┆        ┆ ---        │
│      ┆             ┆             ┆             ┆   ┆            ┆          ┆        ┆ f64        │
╞══════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪══════════╪════════╪════════════╡
│ 1301 ┆ 2017-03-31  ┆ 本          ┆ 2017-05-11  ┆ … ┆ 230.7      ┆ 60.0     ┆ -2     ┆ 63.78      │
│ 1301 ┆ 2018-03-31  ┆ 本          ┆ 2018-05-10  ┆ … ┆ 304.3      ┆ 60.0     ┆ 4      ┆ 57.42      │
│ 1301 ┆ 2018-09-30  ┆ 四          ┆ 2018-11-05  ┆ … ┆ 24.9       ┆ 0.8      ┆ 2      ┆ 102.93     │
│ 1301 ┆ 2018-12-31  ┆ 四          ┆ 2019-02-08  ┆ … ┆ 155.2      ┆ 2.8      ┆ 3      ┆ 30.33      │
│ 1301 ┆ 2019-03-31  ┆ 四          ┆ 2019-05-13  ┆ … ┆ 38.2       ┆ 0.9      ┆ 4      ┆ 114.22     │
│ …    ┆ …           ┆ …           ┆ …           ┆ … ┆ …          ┆ …        ┆ …      ┆ …          │
│ 9997 ┆ 2024-12-31  ┆ 四          ┆ 2025-01-31  ┆ … ┆ 28.9       ┆ 6.1      ┆ 3      ┆ 13.48      │
│ 9997 ┆ 2025-03-31  ┆ 四          ┆ 2025-05-13  ┆ … ┆ 35.7       ┆ 8.7      ┆ 4      ┆ 11.48      │
│ 9997 ┆ 2025-03-31  ┆ 本          ┆ 2025-05-13  ┆ … ┆ 91.3       ┆ 29.0     ┆ 4      ┆ 15.91      │
│ 9997 ┆ 2026-03-31  ┆ 予          ┆ 2025-05-13  ┆ … ┆ 98.7       ┆ 30.0     ┆ 4      ┆ 15.9       │
│ 9997 ┆ 2025-06-30  ┆ 四          ┆ 2025-07-31  ┆ … ┆ 7.7        ┆ 3.1      ┆ 1      ┆ 40.4       │
└──────┴─────────────┴─────────────┴─────────────┴───┴────────────┴──────────┴────────┴────────────┘