In [1]:
#####
##### import objects
#####
from pathlib import Path
import os

CURRENT_DIR = Path(os.getcwd())
PJ_DIR = CURRENT_DIR.parent.parent
DATA_DIR = PJ_DIR / "data" 


from wequant.data_processing import PricelistPl
import polars as pl
from datetime import date

ModuleNotFoundError: No module named 'wequant.data_processing'

In [2]:
# reviced_pricelitの取得
PPL = PricelistPl()

In [6]:
df = PPL.df
df.filter(pl.col("accumulated_split_rate")!=1).sort(["date"], descending=[True])

shape: (4_356_786, 8)
┌──────┬────────────┬────────────┬────────────┬────────────┬────────────┬─────────────┬────────────┐
│ code ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ volume      ┆ accumulate │
│ ---  ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---         ┆ d_split_ra │
│ i64  ┆ date       ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64         ┆ te         │
│      ┆            ┆            ┆            ┆            ┆            ┆             ┆ ---        │
│      ┆            ┆            ┆            ┆            ┆            ┆             ┆ f64        │
╞══════╪════════════╪════════════╪════════════╪════════════╪════════════╪═════════════╪════════════╡
│ 7946 ┆ 2026-03-04 ┆ 662.0      ┆ 684.0      ┆ 626.0      ┆ 668.0      ┆ 12500.0     ┆ 0.2        │
│ 7946 ┆ 2026-03-03 ┆ 746.0      ┆ 746.0      ┆ 642.0      ┆ 676.0      ┆ 36000.0     ┆ 0.2        │
│ 7946 ┆ 2026-03-02 ┆ 740.0      ┆ 776.0      ┆ 685.0      ┆ 746.0      ┆ 36500.0     ┆ 0.2        │
│ 7946 ┆ 2026-02-27 ┆ 783.0      ┆ 784.0      ┆ 702.0      ┆ 747.0      ┆ 77500.0     ┆ 0.2        │
│ 7946 ┆ 2026-02-26 ┆ 808.0      ┆ 948.0      ┆ 700.0      ┆ 769.0      ┆ 305500.0    ┆ 0.2        │
│ …    ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …           ┆ …          │
│ 9987 ┆ 2009-01-05 ┆ 2500.00025 ┆ 2500.00025 ┆ 2400.00024 ┆ 2418.18206 ┆ 120889.9879 ┆ 0.909091   │
│      ┆            ┆            ┆            ┆            ┆            ┆ 11          ┆            │
│ 9989 ┆ 2009-01-05 ┆ 1270.0     ┆ 1270.0     ┆ 1222.5     ┆ 1232.5     ┆ 259400.0    ┆ 0.5        │
│ 9990 ┆ 2009-01-05 ┆ 246.000123 ┆ 258.000129 ┆ 222.673445 ┆ 236.673452 ┆ 47849.97607 ┆ 0.666667   │
│      ┆            ┆            ┆            ┆            ┆            ┆ 5           ┆            │
│ 9994 ┆ 2009-01-05 ┆ 414.554587 ┆ 421.818224 ┆ 414.554587 ┆ 414.554587 ┆ 2199.99978  ┆ 0.909091   │
│ 9997 ┆ 2009-01-05 ┆ 124.0      ┆ 124.0      ┆ 120.0      ┆ 120.0      ┆ 83100.0     ┆ 0.5        │
└──────┴────────────┴────────────┴────────────┴────────────┴────────────┴─────────────┴────────────┘

In [7]:
df.filter(pl.col("code")==7946).filter(pl.col("date")>=date(2026, 3, 1))

shape: (14, 8)
┌──────┬────────────┬───────┬───────┬───────┬───────┬──────────┬────────────────────────┐
│ code ┆ date       ┆ open  ┆ high  ┆ low   ┆ close ┆ volume   ┆ accumulated_split_rate │
│ ---  ┆ ---        ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---      ┆ ---                    │
│ i64  ┆ date       ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64      ┆ f64                    │
╞══════╪════════════╪═══════╪═══════╪═══════╪═══════╪══════════╪════════════════════════╡
│ 7946 ┆ 2026-03-02 ┆ 740.0 ┆ 776.0 ┆ 685.0 ┆ 746.0 ┆ 36500.0  ┆ 0.2                    │
│ 7946 ┆ 2026-03-03 ┆ 746.0 ┆ 746.0 ┆ 642.0 ┆ 676.0 ┆ 36000.0  ┆ 0.2                    │
│ 7946 ┆ 2026-03-04 ┆ 662.0 ┆ 684.0 ┆ 626.0 ┆ 668.0 ┆ 12500.0  ┆ 0.2                    │
│ 7946 ┆ 2026-03-05 ┆ 638.0 ┆ 700.0 ┆ 632.0 ┆ 670.0 ┆ 13800.0  ┆ 1.0                    │
│ 7946 ┆ 2026-03-06 ┆ 660.0 ┆ 666.0 ┆ 617.0 ┆ 620.0 ┆ 21000.0  ┆ 1.0                    │
│ …    ┆ …          ┆ …     ┆ …     ┆ …     ┆ …     ┆ …        ┆ …                      │
│ 7946 ┆ 2026-03-13 ┆ 590.0 ┆ 612.0 ┆ 590.0 ┆ 612.0 ┆ 7100.0   ┆ 1.0                    │
│ 7946 ┆ 2026-03-16 ┆ 612.0 ┆ 613.0 ┆ 602.0 ┆ 605.0 ┆ 1500.0   ┆ 1.0                    │
│ 7946 ┆ 2026-03-17 ┆ 604.0 ┆ 632.0 ┆ 602.0 ┆ 625.0 ┆ 6200.0   ┆ 1.0                    │
│ 7946 ┆ 2026-03-18 ┆ 615.0 ┆ 690.0 ┆ 613.0 ┆ 660.0 ┆ 18500.0  ┆ 1.0                    │
│ 7946 ┆ 2026-03-19 ┆ 659.0 ┆ 760.0 ┆ 620.0 ┆ 760.0 ┆ 103600.0 ┆ 1.0                    │
└──────┴────────────┴───────┴───────┴───────┴───────┴──────────┴────────────────────────┘

In [17]:
df = PPL.df
pdf = df.group_by("code").agg(
    pl.max("date").alias("latest_date")
)
pdf = pdf.sort("code")
pdf = pdf.filter(pl.col("latest_date")==pl.lit(date(2026, 3, 16)))
pdf

shape: (20, 2)
┌──────┬─────────────┐
│ code ┆ latest_date │
│ ---  ┆ ---         │
│ i64  ┆ date        │
╞══════╪═════════════╡
│ 1301 ┆ 2026-03-16  │
│ 1332 ┆ 2026-03-16  │
│ 1333 ┆ 2026-03-16  │
│ 1375 ┆ 2026-03-16  │
│ 1376 ┆ 2026-03-16  │
│ …    ┆ …           │
│ 1417 ┆ 2026-03-16  │
│ 1418 ┆ 2026-03-16  │
│ 1419 ┆ 2026-03-16  │
│ 1420 ┆ 2026-03-16  │
│ 1429 ┆ 2026-03-16  │
└──────┴─────────────┘

In [8]:
df.filter(pl.col("code")==1301)

shape: (4_204, 8)
┌──────┬────────────┬────────┬────────┬────────┬────────┬─────────┬────────────────────────┐
│ code ┆ date       ┆ open   ┆ high   ┆ low    ┆ close  ┆ volume  ┆ accumulated_split_rate │
│ ---  ┆ ---        ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---     ┆ ---                    │
│ i64  ┆ date       ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ f64     ┆ f64                    │
╞══════╪════════════╪════════╪════════╪════════╪════════╪═════════╪════════════════════════╡
│ 1301 ┆ 2009-01-05 ┆ 2100.0 ┆ 2120.0 ┆ 2060.0 ┆ 2070.0 ┆ 11500.0 ┆ 10.0                   │
│ 1301 ┆ 2009-01-06 ┆ 2070.0 ┆ 2090.0 ┆ 2050.0 ┆ 2070.0 ┆ 27300.0 ┆ 10.0                   │
│ 1301 ┆ 2009-01-07 ┆ 2050.0 ┆ 2080.0 ┆ 2050.0 ┆ 2070.0 ┆ 26900.0 ┆ 10.0                   │
│ 1301 ┆ 2009-01-08 ┆ 2050.0 ┆ 2070.0 ┆ 2040.0 ┆ 2060.0 ┆ 19900.0 ┆ 10.0                   │
│ 1301 ┆ 2009-01-09 ┆ 2070.0 ┆ 2080.0 ┆ 2050.0 ┆ 2050.0 ┆ 24300.0 ┆ 10.0                   │
│ …    ┆ …          ┆ …      ┆ …      ┆ …      ┆ …      ┆ …       ┆ …                      │
│ 1301 ┆ 2026-03-10 ┆ 5250.0 ┆ 5290.0 ┆ 5210.0 ┆ 5250.0 ┆ 38900.0 ┆ 1.0                    │
│ 1301 ┆ 2026-03-11 ┆ 5290.0 ┆ 5350.0 ┆ 5280.0 ┆ 5280.0 ┆ 27900.0 ┆ 1.0                    │
│ 1301 ┆ 2026-03-12 ┆ 5250.0 ┆ 5260.0 ┆ 5070.0 ┆ 5100.0 ┆ 56100.0 ┆ 1.0                    │
│ 1301 ┆ 2026-03-13 ┆ 5080.0 ┆ 5130.0 ┆ 5080.0 ┆ 5090.0 ┆ 45200.0 ┆ 1.0                    │
│ 1301 ┆ 2026-03-16 ┆ 5070.0 ┆ 5090.0 ┆ 5030.0 ┆ 5050.0 ┆ 39500.0 ┆ 1.0                    │
└──────┴────────────┴────────┴────────┴────────┴────────┴─────────┴────────────────────────┘

In [3]:
PPL.get_downrate_from_max_and_increserate_from_min()

shape: (3_759, 12)
┌──────┬────────────┬────────┬────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ code ┆ date       ┆ open   ┆ high   ┆ … ┆ downrate_fro ┆ increserate ┆ days_since_ ┆ days_since_ │
│ ---  ┆ ---        ┆ ---    ┆ ---    ┆   ┆ m_max        ┆ _from_min   ┆ max         ┆ min         │
│ i64  ┆ date       ┆ f64    ┆ f64    ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│      ┆            ┆        ┆        ┆   ┆ f64          ┆ f64         ┆ duration[ms ┆ duration[ms │
│      ┆            ┆        ┆        ┆   ┆              ┆             ┆ ]           ┆ ]           │
╞══════╪════════════╪════════╪════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1301 ┆ 2025-10-17 ┆ 4870.0 ┆ 4900.0 ┆ … ┆ -6.97        ┆ 2.09        ┆ 38d         ┆ 3d          │
│ 1332 ┆ 2025-10-17 ┆ 1047.0 ┆ 1057.5 ┆ … ┆ -3.61        ┆ 3.24        ┆ 9d          ┆ 3d          │
│ 1333 ┆ 2025-10-17 ┆ 3397.0 ┆ 3410.0 ┆ … ┆ -34.75       ┆ 84.13       ┆ 2668d       ┆ 2044d       │
│ 1375 ┆ 2025-10-17 ┆ 1038.0 ┆ 1040.0 ┆ … ┆ -109.55      ┆ 27.4        ┆ 1815d       ┆ 1239d       │
│ 1376 ┆ 2025-10-17 ┆ 1751.0 ┆ 1820.0 ┆ … ┆ -5.0         ┆ 35.8        ┆ 1264d       ┆ 193d        │
│ …    ┆ …          ┆ …      ┆ …      ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 9991 ┆ 2025-10-17 ┆ 1386.0 ┆ 1386.0 ┆ … ┆ -41.71       ┆ 105.86      ┆ 4062d       ┆ 2040d       │
│ 9993 ┆ 2025-10-17 ┆ 1165.0 ┆ 1176.0 ┆ … ┆ -77.72       ┆ 8.39        ┆ 2636d       ┆ 154d        │
│ 9994 ┆ 2025-10-17 ┆ 2308.0 ┆ 2312.0 ┆ … ┆ -81.5        ┆ 25.86       ┆ 2716d       ┆ 2040d       │
│ 9996 ┆ 2025-10-17 ┆ 2000.0 ┆ 2015.0 ┆ … ┆ -17.12       ┆ 12.51       ┆ 213d        ┆ 189d        │
│ 9997 ┆ 2025-10-17 ┆ 995.0  ┆ 999.0  ┆ … ┆ -53.96       ┆ 153.69      ┆ 2815d       ┆ 2038d       │
└──────┴────────────┴────────┴────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [3]:
###
### def get_downrate_from_max_and_increserate_from_min(
###     self, 
###     valuation_date: date = date.today(),
###     max_price_type: Literal["high", "close"] = "high",
###     min_price_type: Literal["low", "close"] = "low"
### )
###

# import objects required
from datetime import date
from typing import Literal
import polars as pl

# set parametor
self = PPL
valuation_date = date.today()
max_price_type = "high"
min_price_type = "low"

In [4]:
# body
# 元の列を保存
ori_cols = self.df.columns

# 各銘柄の最高値を記録した日付、最高値の株価のリストを取得
df1 = self.get_max_pricelist_rec(
    valuation_date = valuation_date,
    price_type = max_price_type
)

In [5]:
# 各銘柄の最高値記録後における最安値を記録した日付、最安値の株価のリストを取得
df2 = self.df
df2 = (
    df2
    .join(df1, on=["code"], how="left")
    .filter(pl.col("date") > pl.col("max_date"))
    .sort(by=["code", min_price_type, "date"], descending=[False, False, True])
    .group_by("code")
    .head(1)
    .select(["code", "max_date", f'max_{max_price_type}', "date", min_price_type])
    .rename({
        "date": "min_date",
        min_price_type: f'min_{min_price_type}'
    })
)

In [6]:
# valuation_dateにおける銘柄ごとの株価リストを取得
df3 = self.df
df3 = (
    df3
    .filter(pl.col("date")<pl.lit(valuation_date))
    .sort(by=["code", "date"], descending=[False, True])
    .group_by("code")
    .head(1)
    .join(df2, on=["code"], how="left")
)

In [9]:
# 出力データの加工
df3 = (
    df3
    .with_columns([
        (pl.lit(100) * (pl.col("close") - pl.col(f'max_{max_price_type}')) / pl.col("close")).round(2).alias("downrate_from_max"),
        (pl.lit(100) * (pl.col("close") - pl.col(f'min_{min_price_type}')) / pl.col(f'min_{min_price_type}')).round(2).alias("increserate_from_min"),
        (pl.col("date") - pl.col("max_date")).alias("days_since_max"),
        (pl.col("date") - pl.col("min_date")).alias("days_since_min")
    ])  
)
df3_columns = df3.columns
df3 = df3.select(ori_cols + df3_columns[-4:])

In [17]:
from datetime import timedelta

valid_duration = timedelta(days=3)
last_date = df3["date"].max()
valid_date = last_date - valid_duration
df3 = (
    df3.with_columns([
        pl.lit(valid_date).alias("valid_date")
    ])
)

In [21]:
df3_cols = df3.columns
df3 = (
    df3
    .filter(pl.col("date")>=pl.col("valid_date"))
    .select(df3_cols[:-1])
)

In [22]:
df3

shape: (3_759, 12)
┌──────┬────────────┬────────┬────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ code ┆ date       ┆ open   ┆ high   ┆ … ┆ downrate_fro ┆ increserate ┆ days_since_ ┆ days_since_ │
│ ---  ┆ ---        ┆ ---    ┆ ---    ┆   ┆ m_max        ┆ _from_min   ┆ max         ┆ min         │
│ i64  ┆ date       ┆ f64    ┆ f64    ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│      ┆            ┆        ┆        ┆   ┆ f64          ┆ f64         ┆ duration[ms ┆ duration[ms │
│      ┆            ┆        ┆        ┆   ┆              ┆             ┆ ]           ┆ ]           │
╞══════╪════════════╪════════╪════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1301 ┆ 2025-10-17 ┆ 4870.0 ┆ 4900.0 ┆ … ┆ -6.97        ┆ 2.09        ┆ 38d         ┆ 3d          │
│ 1332 ┆ 2025-10-17 ┆ 1047.0 ┆ 1057.5 ┆ … ┆ -3.61        ┆ 3.24        ┆ 9d          ┆ 3d          │
│ 1333 ┆ 2025-10-17 ┆ 3397.0 ┆ 3410.0 ┆ … ┆ -34.75       ┆ 84.13       ┆ 2668d       ┆ 2044d       │
│ 1375 ┆ 2025-10-17 ┆ 1038.0 ┆ 1040.0 ┆ … ┆ -109.55      ┆ 27.4        ┆ 1815d       ┆ 1239d       │
│ 1376 ┆ 2025-10-17 ┆ 1751.0 ┆ 1820.0 ┆ … ┆ -5.0         ┆ 35.8        ┆ 1264d       ┆ 193d        │
│ …    ┆ …          ┆ …      ┆ …      ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 9991 ┆ 2025-10-17 ┆ 1386.0 ┆ 1386.0 ┆ … ┆ -41.71       ┆ 105.86      ┆ 4062d       ┆ 2040d       │
│ 9993 ┆ 2025-10-17 ┆ 1165.0 ┆ 1176.0 ┆ … ┆ -77.72       ┆ 8.39        ┆ 2636d       ┆ 154d        │
│ 9994 ┆ 2025-10-17 ┆ 2308.0 ┆ 2312.0 ┆ … ┆ -81.5        ┆ 25.86       ┆ 2716d       ┆ 2040d       │
│ 9996 ┆ 2025-10-17 ┆ 2000.0 ┆ 2015.0 ┆ … ┆ -17.12       ┆ 12.51       ┆ 213d        ┆ 189d        │
│ 9997 ┆ 2025-10-17 ┆ 995.0  ┆ 999.0  ┆ … ┆ -53.96       ┆ 153.69      ┆ 2815d       ┆ 2038d       │
└──────┴────────────┴────────┴────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘