In [1]:
#####
# 1.最新四半期決算の営業利益率は低い
# 2.最新四半期決算の売上高成長率が10%以上
# 3.最新四半期決算の対売上高営業利益成長率が20%以上
# 4.次期決算を、以下の方法で予測した場合において、営業利益率が前年同期比2倍以上になる
# --> 最新四半期決算の売上高成長率と対売上高営業利益成長率を、次期前年四半期決算に適用して次期決算を予想する

In [2]:
# 読み込みファイルパスの設定とimportしたいmoduleパス(pythonパス)の設定
from pathlib import Path
import os

CURRENT_DIR = Path(os.getcwd())
PJ_DIR = CURRENT_DIR.parent.parent
DATA_DIR = PJ_DIR / "data" 



# notebook内で利用するmoduleのimport
from wequant.data_processing import KessanPl, PricelistFig, PricelistPl, MeigaralistPl
from wequant.data_processing import ShikihoOnlinePl, FinancequotePl, print_finance_quote, PricelistFig, KessanFig, IndexPricelistPl
import polars as pl
from datetime import date
from dateutil.relativedelta import relativedelta

RevPl = PricelistPl("reviced_pricelist.parquet")
RawPL = PricelistPl("raw_pricelist.parquet")
MPL = MeigaralistPl()
SPL = ShikihoOnlinePl()

In [3]:
KPL = KessanPl()
KPL.with_columns_lastyear_settlement()
df1 = KPL.df.filter(pl.col("settlement_type")=="四")
df1 = df1.with_columns([
    pl.col("settlement_date").alias("key")
])

In [4]:
# para
valuation_date = date(2023, 9, 15)
valuation_date = date.today()

KPL = KessanPl()
df2 = KPL.get_settlement_forcast_by_diff_growth_rate(valuation_date)
df2 = df2.filter(pl.col("settlement_type")=="四")
df2 = df2.with_columns([
    pl.col("nxt_settlement_date").alias("key")
])

In [5]:
KPL = KessanPl()
df3 = KPL.get_current_settlements(valuation_date)
df3 = df3.filter(pl.col("settlement_type")=="四")
df3 = df3.with_columns([
    pl.col("settlement_date").alias("key")
])

In [6]:
KPL = KessanPl()
df = KPL.get_settlement_updown_rate("四")
df = df.with_columns([
    pl.col("settlement_date").alias("key")
])
df4 = df.select(["code", "key", "updown_rate", "nh_updown_rate"])
# df4.filter(pl.col("code")==9022)

In [7]:
# df1, df2, df3, df4をjoin&select
df = df2.join(df1, on=["code", "key"], how="left")
df21 = df

df = df21.with_columns([
    pl.col("settlement_date").alias("lst_settlement_date"),
    pl.col("announcement_date").alias("lst_announcement_date"),
    pl.col("settlement_type").alias("lst_settlement_type"),
    pl.col("sales").alias("lst_sales"),
    pl.col("operating_income").alias("lst_operating_income"),
    pl.col("ordinary_profit").alias("lst_ordinary_profit"),
    pl.col("final_profit").alias("lst_final_profit"),
    pl.col("quater").alias("lst_quater")
])
df = df.select([
    "code",	
    "lst_settlement_date",
    "lst_announcement_date",
    "lst_settlement_type",
    'lst_sales',
    'lst_operating_income',
    'lst_ordinary_profit',
    'lst_final_profit',
    "quater",
    "ly_settlement_date",
    "ly_sales",
    "ly_operating_income",
    "ly_ordinary_profit",
    "ly_final_profit",
    "nxt_settlement_date",
    "fcst_dgr_sales",
    "fcst_dgr_operating_income",
    "fcst_dgr_ordinary_profit",	
    "fcst_dgr_final_profit",
    "key"
])
df = df.join(df3, on=["code", "key"], how="left")
df = df.drop_nulls()

df123 = df

In [8]:
# ly_fcstの売上高、営業利益成長率を
# 列名ly_fcst_sales_gr, ly_fcst_operating_income_grで追加
df = df123.with_columns([
    (pl.lit(100) * pl.col("lst_operating_income") / pl.col("lst_sales")).round(2).alias("lst_operating_income_pr"),
    (pl.lit(100) * (pl.col("fcst_dgr_sales") - pl.col("ly_sales")) / pl.col("ly_sales")).round(2).alias("ly_fcst_sales_gr"),
    (pl.lit(100) * (pl.col("fcst_dgr_operating_income") - pl.col("ly_operating_income")) / pl.col("ly_operating_income")).round(2).alias("ly_fcst_operating_income_gr"),
])

df = df.join(df4, on=["code", "key"], how="left")
df = df.drop_nulls()

scols = [
    "code",
    "lst_settlement_date",
    #lst_announcement_date,
    #lst_settlement_type,
    "lst_sales",
    "lst_operating_income",
    "lst_ordinary_profit",
    "lst_final_profit",
    "quater",
    #ly_settlement_date,
    "ly_sales",
    "ly_operating_income",
    #ly_ordinary_profit,
    #ly_final_profit,
    #nxt_settlement_date,
    "fcst_dgr_sales",
    "fcst_dgr_operating_income",
    "fcst_dgr_ordinary_profit",
    "fcst_dgr_final_profit",
    #key,
    #settlement_date,
    #settlement_type,
    #announcement_date,
    "sales",
    "operating_income",
    "ordinary_profit",
    "final_profit",
    #reviced_eps,
    #dividend,
    #quater_right,
    "lst_operating_income_pr",
    "ly_fcst_sales_gr",
    "ly_fcst_operating_income_gr",
    "updown_rate",
    "nh_updown_rate"
]
df = df.select(scols)
codes = df["code"].unique()
df = df.sort(by=["ly_fcst_operating_income_gr"], descending=[True])
original_df = df
original_df

shape: (0, 22)
┌──────┬────────────┬───────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ code ┆ lst_settle ┆ lst_sales ┆ lst_operat ┆ … ┆ ly_fcst_sa ┆ ly_fcst_op ┆ updown_ra ┆ nh_updown │
│ ---  ┆ ment_date  ┆ ---       ┆ ing_income ┆   ┆ les_gr     ┆ erating_in ┆ te        ┆ _rate     │
│ i64  ┆ ---        ┆ i64       ┆ ---        ┆   ┆ ---        ┆ come_gr    ┆ ---       ┆ ---       │
│      ┆ date       ┆           ┆ i64        ┆   ┆ f64        ┆ ---        ┆ f64       ┆ f64       │
│      ┆            ┆           ┆            ┆   ┆            ┆ f64        ┆           ┆           │
╞══════╪════════════╪═══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
└──────┴────────────┴───────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [9]:
######
###### filter
######

In [10]:
# 昨年同期営業利益マイナス
# 前四半期営業利益マイナス
# 今四半期予想前年同期売上高10%成長
# 今四半期予想営業利益プラス
# 今四半期売上高差分営業利益プラス20%
min_ly_operating_income = -999999999
max_ly_operating_income = 0

min_lst_operating_income_pr = -99999999
max_lst_operating_income_pr = 0

min_ly_fcst_sales_gr = 10
max_ly_fcst_sales_gr = 999999999

min_ly_fcst_operating_income_gr = -999999999	
max_ly_fcst_operating_income_gr	= 0

min_fcst_dgr_operating_income = 20
max_fcst_dgr_operating_income = 999999999

In [11]:
df = original_df

df = df\
    .filter(pl.col("ly_operating_income") >= min_ly_operating_income)\
    .filter(pl.col("ly_operating_income")  < max_ly_operating_income)\
\
    .filter(pl.col("lst_operating_income_pr") >= min_lst_operating_income_pr)\
    .filter(pl.col("lst_operating_income_pr") < max_lst_operating_income_pr)\
\
    .filter(pl.col("ly_fcst_sales_gr") >= min_ly_fcst_sales_gr)\
    .filter(pl.col("ly_fcst_sales_gr") < max_ly_fcst_sales_gr)\
\
    .filter(pl.col("ly_fcst_operating_income_gr") >= min_ly_fcst_operating_income_gr)\
    .filter(pl.col("ly_fcst_operating_income_gr") < max_ly_fcst_operating_income_gr)\
\
    .filter(pl.col("fcst_dgr_operating_income") >= min_fcst_dgr_operating_income)\
    .filter(pl.col("fcst_dgr_operating_income") <  max_fcst_dgr_operating_income)

filtered_df = df
pl.Config(tbl_rows=df.shape[0])
pl.Config.set_tbl_cols(df.shape[1])
df

shape: (0, 22)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ cod ┆ lst ┆ lst ┆ lst ┆ lst ┆ lst ┆ qua ┆ ly_ ┆ ly_ ┆ fcs ┆ fcs ┆ fcs ┆ fcs ┆ sal ┆ ope ┆ ord ┆ fin ┆ lst ┆ ly_ ┆ ly_ ┆ upd ┆ nh_ │
│ e   ┆ _se ┆ _sa ┆ _op ┆ _or ┆ _fi ┆ ter ┆ sal ┆ ope ┆ t_d ┆ t_d ┆ t_d ┆ t_d ┆ es  ┆ rat ┆ ina ┆ al_ ┆ _op ┆ fcs ┆ fcs ┆ own ┆ upd │
│ --- ┆ ttl ┆ les ┆ era ┆ din ┆ nal ┆ --- ┆ es  ┆ rat ┆ gr_ ┆ gr_ ┆ gr_ ┆ gr_ ┆ --- ┆ ing ┆ ry_ ┆ pro ┆ era ┆ t_s ┆ t_o ┆ _ra ┆ own │
│ i64 ┆ eme ┆ --- ┆ tin ┆ ary ┆ _pr ┆ i64 ┆ --- ┆ ing ┆ sal ┆ ope ┆ ord ┆ fin ┆ i64 ┆ _in ┆ pro ┆ fit ┆ tin ┆ ale ┆ per ┆ te  ┆ _ra │
│     ┆ nt_ ┆ i64 ┆ g_i ┆ _pr ┆ ofi ┆     ┆ i64 ┆ _in ┆ es  ┆ rat ┆ ina ┆ al_ ┆     ┆ com ┆ fit ┆ --- ┆ g_i ┆ s_g ┆ ati ┆ --- ┆ te  │
│     ┆ dat ┆     ┆ nco ┆ ofi ┆ t   ┆     ┆     ┆ com ┆ --- ┆ ing ┆ ry_ ┆ pro ┆     ┆ e   ┆ --- ┆ i64 ┆ nco ┆ r   ┆ ng_ ┆ f64 ┆ --- │
│     ┆ e   ┆     ┆ me  ┆ t   ┆ --- ┆     ┆     ┆ e   ┆ i64 ┆ _in ┆ pro ┆ fit ┆     ┆ --- ┆ i64 ┆     ┆ me_ ┆ --- ┆ inc ┆     ┆ f64 │
│     ┆ --- ┆     ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆ --- ┆     ┆ com ┆ fit ┆ --- ┆     ┆ i64 ┆     ┆     ┆ pr  ┆ f64 ┆ ome ┆     ┆     │
│     ┆ dat ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ e   ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ _gr ┆     ┆     │
│     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [12]:
df = original_df

print("##### 全体")
print(f'総銘柄数：{df.shape[0]}')
a = df.filter(pl.col("updown_rate")>0).shape[0]
b = df.filter(pl.col("updown_rate")<=0).shape[0]
uprate = round(100*a/(a+b), 1)
print(f'上昇銘柄数:{a}／下落銘柄数:{b}／上昇率:({uprate}%)')
print(f'全銘柄平均騰落率:{round(df["updown_rate"].mean(), 2)}%')
print(f'日経225平均騰落率:{round(df["nh_updown_rate"].mean(), 2)}%')
print()

df = filtered_df
print("##### 抽出銘柄")
print(f'総銘柄数：{df.shape[0]}')
a = df.filter(pl.col("updown_rate")>0).shape[0]
b = df.filter(pl.col("updown_rate")<=0).shape[0]
uprate = round(100*a/(a+b), 1)
print(f'上昇銘柄数:{a}／下落銘柄数:{b}／上昇率:({uprate}%)')
print(f'抽出銘柄平均騰落率:{round(df["updown_rate"].mean(), 2)}%')
print(f'日経225平均騰落率:{round(df["nh_updown_rate"].mean(), 2)}%')

##### 全体
総銘柄数：0

ZeroDivisionError: division by zero

In [ ]:
#####
##### 個別銘柄の分析
#####

In [ ]:
# 四季報
code = 3237
SPL.print_stock_df(code, num=4, valuation_date=valuation_date)

In [ ]:
KFIG = KessanFig(code, "四半期", end_settlement_date=valuation_date)
KFIG.add_trace_profits()
KFIG.fig.show()

In [ ]:
# 日足
delta = relativedelta(days=100)

KPL = KessanPl()
df = KPL.df.filter(pl.col("announcement_date")<valuation_date).filter(pl.col("code")==code)
ann_date = df["announcement_date"].to_list()[-1]
print(f'決算発表日: {ann_date}')
start_date = ann_date - delta
end_date = ann_date + delta

PFIG = PricelistFig(code, RevPl.df, MPL.df, start_date, end_date)
# 決算発表日にvlineを引く
PFIG.add_vline_announcement_date()
PFIG.add_vline(valuation_date)
PFIG.fig.show()